import 'package:flutter/material.dart';

class CategoryIcon {
  static const Map<String, IconData> _categoryIcons = {
    'books': Icons.book,
    'electronics': Icons.electrical_services,
    'furniture': Icons.chair,
    'toys': Icons.toys,
    'clothing': Icons.checkroom,
    'shoes': Icons.hiking,
    'accessories': Icons.style,
    'home decor': Icons.home,
    'kitchenware': Icons.kitchen,
    'sports equipment': Icons.sports,
    'outdoor gear': Icons.outdoor_grill,
    'tools': Icons.build,
    'garden supplies': Icons.local_florist,
    'automotive parts': Icons.car_repair,
    'office supplies': Icons.local_offer,
    'pet supplies': Icons.pets,
    'health and beauty': Icons.health_and_safety,
    'groceries': Icons.local_grocery_store,
    'jewelry': Icons.watch,
    'watches': Icons.watch,
    'musical instruments': Icons.music_note,
    'art supplies': Icons.palette,
    'craft supplies': Icons.brush,
    'baby products': Icons.baby_changing_station,
    'bicycles': Icons.directions_bike,
    'video games': Icons.videogame_asset,
    'movies': Icons.movie,
    'board games': Icons.casino,
    'collectibles': Icons.collections,
    'antiques': Icons.emoji_objects,
    'comics': Icons.collections_bookmark,
    'luggage': Icons.luggage,
    'handbags': Icons.shopping_bag,
    'wallets': Icons.account_balance_wallet,
    'sunglasses': Icons.wb_sunny,
    'hats': Icons.emoji_people,
    'scarves': Icons.face,
    'gloves': Icons.handshake,
    'belts': Icons.no_encryption,
    'umbrellas': Icons.umbrella,
    'cell phones': Icons.phone_android,
    'tablets': Icons.tablet,
    'laptops': Icons.laptop,
    'desktops': Icons.desktop_windows,
    'printers': Icons.print,
    'scanners': Icons.scanner,
    'monitors': Icons.tv,
    'speakers': Icons.speaker,
    'headphones': Icons.headset,
    'cameras': Icons.camera,
    'drones': Icons.airplanemode_active,
  };

  static Icon getIcon(String category,
      {double iconSize = 24, Color iconColor = Colors.black54}) {
    return Icon(
      _categoryIcons[category.toLowerCase()] ?? Icons.help_outline,
      size: iconSize,
      color: iconColor,
    );
  }
}
